### PR TITLE
implement bind directive

### LINKED ISSUE #4: Implement lit-html directive for two way binding
see Polymer/lit-html#573

### PR DESCRIPTION
**Pull request by morbidick**
closes #4 

TODO:
  * [x] document
  * [x] move notify mixin to notify.js and export both via index.js, update package.json main field

### CODE REVIEW

**Comment by morbidick** [comment]
naming is hard, im not really satisfied with `bind`, any ideas?

* bind
* subscribe
* twoway

**Comment by FluorescentHallucinogen** [comment]
@morbidick It seems I don't understand fully the idea of this directive. Could you please explain on code samples?

**Comment by morbidick** [comment]
The idea is to simplify two way data binding similar to the "polymer way" with the double curly braces`. With pure lit-html you would currently need to write:

```js
html`<element .value=${this.myProperty} @value-changed=${(e) => this.myProperty = e.detail.value}`></element>
```

with this directive this would be:

```js
html`<element .value=${bind(this, 'myProperty')}></element>
```


**Sidenote**:
similar to the polymer implementation it [reads the sibling property directly](https://github.com/morbidick/lit-element-notify/pull/5/files#diff-d5e024561b2d6152b97bb97ec8435aa2R23) and ignores the event value, I'm not sure which way i prefer. Some input on that would be nice :)

I'll try to add a similar explanation to the Readme in the PR.

**Comment by FluorescentHallucinogen** [comment]
@morbidick Sorry for the late input. What is `this` in `${bind(this, 'myProperty')}`? Could there be something else instead of `this`? If not, what about a more simple syntax with a single argument (and another name) for this directive? Something like:

```js
html`
  <one-element .value=${sync('myProperty')}></one-element>
  <another-element .value=${sync('myProperty')}></another-element>
`
```

**Comment by morbidick** [comment]
We need to inject this (the current component) into the directive because the directive has it not in its context. I havent found a better way yet. Naming input is very welcome since im not really happy with it, but im not sure how to get to a decision since all proposals until now are just oki-ish (thats at least how i feel).

**Comment by FluorescentHallucinogen** [comment]
@morbidick About naming: IMO, "subscribe" sounds like something one-way, "sync" sounds bidirectional.

**Comment by morbidick** [comment]
thats a fair point and its shorter :) Would be awesome to have more eyes on this and the readme.

**Comment by morbidick** [comment]
just updated to sync in #9 and got to say the readme reads a lot nicer!

**Comment by morbidick** [comment]
@FluorescentHallucinogen i just had another good sleep over this problem and had two ideas for implementations that have access to the parent element, that would result in one of the two syntaxes:

```js
// as eventPart
html`<element @value=${sync('myProperty')></element>`

// as class mixin that returns the directive
html`<element .value=${this.sync('myProperty')></element>`
```

i like the second syntax better.

**Comment by FluorescentHallucinogen** [comment]
@morbidick The second option is :fire:.

**Pull request merged**
